# Generated by Django 5.0 on 2023-12-17 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerji_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hastalik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastalik_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ilaclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac_adi', models.CharField(max_length=255)),
                ('firma_adi', models.CharField(max_length=255)),
                ('recete_turu', models.CharField(max_length=255)),
                ('ithal_imal', models.CharField(max_length=255)),
                ('fiyat', models.FloatField()),
                ('yas_araligi', models.CharField(max_length=255)),
                ('cinsiyet', models.CharField(max_length=255)),
                ('dozu', models.IntegerField()),
                ('turu', models.CharField(max_length=255)),
                ('kullanim_periyodu', models.CharField(max_length=255)),
                ('kullanimi_durumu', models.CharField(max_length=255)),
                ('nasil_kullanilir', models.CharField(max_length=255)),
                ('etkin_madde_adi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kullanici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('soyad', models.CharField(max_length=255)),
                ('dogum_tarihi', models.DateField()),
                ('kilo', models.FloatField()),
                ('kan_grubu', models.CharField(max_length=255)),
                ('cinsyet', models.BooleanField(default=True)),
                ('gebelik', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='KullaniciAlerjileri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alerji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.alerji')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='KullaniciHastaliklari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hastalik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.hastalik')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.kullanici')),
            ],
        ),
        migrations.CreateModel(
            name='KullaniciIlaclari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.ilaclar')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicinequiry.kullanici')),
            ],
        ),
    ]
