# Generated by Django 5.0 on 2023-12-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilaclar',
            name='kullanimi_durumu',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ilaclar',
            name='nasil_kullanilir',
            field=models.TextField(max_length=255),
        ),
    ]
