# Generated by Django 5.0 on 2023-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0002_alter_ilaclar_kullanimi_durumu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilaclar',
            name='fiyat',
            field=models.CharField(max_length=255),
        ),
    ]
