# Generated by Django 5.0 on 2023-12-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0003_alter_ilaclar_fiyat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilaclar',
            name='dozu',
            field=models.CharField(max_length=255),
        ),
    ]
