# Generated by Django 5.0 on 2023-12-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0004_alter_ilaclar_dozu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanici',
            name='password',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kullanici',
            name='tc_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
