# Generated by Django 5.0 on 2024-01-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0005_kullanici_password_kullanici_tc_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kullanici',
            name='cinsyet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kullanici',
            name='gebelik',
            field=models.CharField(max_length=255),
        ),
    ]
