# Generated by Django 5.0 on 2024-01-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicinequiry', '0006_alter_kullanici_cinsyet_alter_kullanici_gebelik'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kullanici',
            old_name='cinsyet',
            new_name='cinsiyet',
        ),
    ]
